In [45]:
import math
import numpy as np
def generate_data(size, d, trans = False):
    assert size > 0 and d > 5
    x = []
    x.append(np.ones(size))
    x.append(np.random.normal(3, 1, size))
    x.append(np.random.normal(-2, 1, size))
    x.append(x[0] + 2 * x[1])
    x.append((x[1] + 2)**2)
    x.append(np.random.binomial(n=1, p=0.8, size=size))
    for _ in range(d - 5):
        x.append(np.random.normal(0, 0.1, size))
    xnp = np.array(x)
    return xnp.T if trans else xnp

In [4]:
X = generate_data(10000, 10)

In [5]:
type(X)

numpy.ndarray

In [6]:
X

array([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 2.10356829e+00,  3.30841288e+00,  3.77181956e+00, ...,
         3.69997718e+00, -3.87390292e-03,  3.24456124e+00],
       [-1.85522951e+00, -4.19607698e+00, -8.61761538e-01, ...,
        -3.38377711e-01, -1.59706893e+00, -1.93237680e+00],
       ...,
       [-3.73513407e-02, -3.86698403e-02,  1.26539927e-01, ...,
         1.17661589e-01, -1.48047573e-01,  1.57629462e-01],
       [ 1.56976867e-01,  3.18981366e-02,  1.67078940e-01, ...,
        -4.55023868e-03, -5.77930140e-02,  6.86379132e-02],
       [-1.35793379e-01, -8.27085909e-02,  2.61349812e-02, ...,
         9.01841512e-02, -4.80885967e-02, -5.03105861e-02]])

In [7]:
X.T

array([[ 1.00000000e+00,  2.10356829e+00, -1.85522951e+00, ...,
        -3.73513407e-02,  1.56976867e-01, -1.35793379e-01],
       [ 1.00000000e+00,  3.30841288e+00, -4.19607698e+00, ...,
        -3.86698403e-02,  3.18981366e-02, -8.27085909e-02],
       [ 1.00000000e+00,  3.77181956e+00, -8.61761538e-01, ...,
         1.26539927e-01,  1.67078940e-01,  2.61349812e-02],
       ...,
       [ 1.00000000e+00,  3.69997718e+00, -3.38377711e-01, ...,
         1.17661589e-01, -4.55023868e-03,  9.01841512e-02],
       [ 1.00000000e+00, -3.87390292e-03, -1.59706893e+00, ...,
        -1.48047573e-01, -5.77930140e-02, -4.80885967e-02],
       [ 1.00000000e+00,  3.24456124e+00, -1.93237680e+00, ...,
         1.57629462e-01,  6.86379132e-02, -5.03105861e-02]])

In [8]:
X.T.shape

(10000, 11)

In [9]:
X.shape

(11, 10000)

In [10]:
X = X.T

In [11]:
XTX = X.T * X

ValueError: operands could not be broadcast together with shapes (11,10000) (10000,11) 

In [12]:
XTX = np.matmul(X.T, X)

In [13]:
XTX

array([[ 1.00000000e+04,  2.99762011e+04, -1.99736707e+04,
         6.99524022e+04,  2.59633139e+05,  8.01200000e+03,
        -2.33764634e+00,  7.15525828e+00, -7.02512105e+00,
         8.37104107e+00, -1.14644424e+01],
       [ 2.99762011e+04,  9.97283344e+04, -5.98612960e+04,
         2.29432870e+05,  8.77223485e+05,  2.40095929e+04,
        -1.10142232e+01,  1.51567698e+01, -1.30919536e+01,
         1.56880632e+01, -4.20698118e+01],
       [-1.99736707e+04, -5.98612960e+04,  4.99220611e+04,
        -1.39696263e+05, -5.18343111e+05, -1.59626164e+04,
        -1.16033107e+01, -1.37067994e+01,  9.39533028e+00,
        -2.50385163e+01,  1.26002121e+01],
       [ 6.99524022e+04,  2.29432870e+05, -1.39696263e+05,
         5.28818142e+05,  2.01408011e+06,  5.60311858e+04,
        -2.43660928e+01,  3.74687980e+01, -3.32090282e+01,
         3.97471676e+01, -9.56040659e+01],
       [ 2.59633139e+05,  8.77223485e+05, -5.18343111e+05,
         2.01408011e+06,  7.75382706e+06,  2.07941179e+05,
  

In [14]:
XTX.shape

(11, 11)

In [13]:
def compute_y(x):
    y = 4 - 3 * x[0] * x[0] + x[2] - 0.01 * x[3] + x[1] * x[4] + np.random.normal(0, 0.1, len(x[0]))
    return y
Y = compute_y(X.T)

In [16]:
Y

array([ 34.51609204,  90.02249694, 125.79673245, ..., 120.78699167,
        -0.65218824,  88.23318165])

In [20]:
np.linalg.eigvals(XTX)

array([8.42593582e+06, 1.82335159e+04, 4.45216061e+03, 1.48994232e+03,
       2.20109153e-11, 1.96345916e+02, 9.51454810e+01, 9.73098499e+01,
       1.04877435e+02, 1.02989660e+02, 1.03550612e+02])

In [26]:
XTXinv = np.linalg.inv(XTX)

In [27]:
ws = np.matmul(XTXinv, X.T)

In [28]:
ws = np.matmul(ws, Y)

In [29]:
ws

array([-1.51778948e+02, -1.09075711e+02,  1.01458702e+00,  2.37093451e+01,
        1.30777672e+01,  6.31444845e-02,  1.24295043e-01, -3.23871170e-01,
        7.16909661e-02,  4.42744400e-01, -1.57435501e-01])

In [30]:
test = generate_data(1000, 10)

In [31]:
ws.shape

(11,)

In [51]:
test = generate_data(1000, 10, False)

In [52]:
test.shape

(11, 1000)

In [53]:
Ytest = compute_y(test)

In [54]:
Ytest.shape

(1000,)

In [55]:
test = test.T

In [56]:
t = test[0]

In [58]:
np.matmul(ws, t.T)

16.668984479184957

In [60]:
Ytest[1]

34.76881917732274

In [62]:
test[0].shape

(11,)

In [63]:
ws.shape

(11,)

In [64]:
ws

array([-1.51778948e+02, -1.09075711e+02,  1.01458702e+00,  2.37093451e+01,
        1.30777672e+01,  6.31444845e-02,  1.24295043e-01, -3.23871170e-01,
        7.16909661e-02,  4.42744400e-01, -1.57435501e-01])

In [67]:
test[0].T

array([ 1.00000000e+00,  3.05868110e+00, -1.32954010e+00,  7.11736220e+00,
        2.55902545e+01,  1.00000000e+00, -4.80154771e-02, -1.19046909e-02,
       -2.39005083e-01, -1.39324366e-01, -1.97437748e-01])

In [68]:
np.matmul(ws, test[0].T)

16.668984479184957

In [69]:
np.matmul(ws, test[0])

16.668984479184957

In [72]:
ws

array([-1.51778948e+02, -1.09075711e+02,  1.01458702e+00,  2.37093451e+01,
        1.30777672e+01,  6.31444845e-02,  1.24295043e-01, -3.23871170e-01,
        7.16909661e-02,  4.42744400e-01, -1.57435501e-01])

In [74]:
np.matmul(ws, test[1])

-39.406187999533955

In [75]:
Ytest[1]

34.76881917732274

In [76]:
np.matmul(ws, test[2])

95.92629819273105

In [77]:
Ytest[2]

144.16278797219277

In [85]:
err = 0
print(Y.shape)
for i in range(len(X)):
    err += abs(Y[i] - np.matmul(ws, X[i])) ** 2

print(err / len(X))

(10000,)
3969.176596596558


In [87]:
err = 0
for i in range(len(test)):
    err += abs(Ytest[i] - np.matmul(ws, test[i])) ** 2

print(err / len(test))

3931.640347093409


In [1]:
import math
import numpy as np
def generate_data(size, d, trans = False):
    assert size > 0 and d > 5
    x = []
    x.append(np.ones(size))
    x.append(np.random.normal(3, 1, size))
    x.append(np.random.normal(-2, 1, size))
    x.append(x[0] + 2 * x[1])
    x.append((x[1] + 2)**2)
    x.append(np.random.binomial(n=1, p=0.8, size=size))
    for _ in range(d - 5):
        x.append(np.random.normal(0, 0.1, size))
    xnp = np.array(x)
    return xnp.T if trans else xnp

In [2]:
X = generate_data(10000, 10, True)

In [3]:
X.shape

(10000, 11)

In [4]:
XTX = np.matmul(X.T, X)

In [5]:
XTX.shape

(11, 11)

In [7]:
np.linalg.eigvals(XTX)

array([8.44344306e+06, 1.79747578e+04, 4.43984101e+03, 1.46363174e+03,
       8.81886019e-11, 1.95672201e+02, 9.71214808e+01, 9.84646337e+01,
       9.93402805e+01, 1.02436430e+02, 1.01122700e+02])

In [8]:
XTXinv = np.linalg.inv(XTX)

In [9]:
XTXinv.shape

(11, 11)

In [10]:
w = np.matmul(XTXinv, X.T)

In [11]:
compute_y

NameError: name 'compute_y' is not defined

In [12]:
Y = compute_y(X.T)

NameError: name 'compute_y' is not defined

In [14]:
Y.shape

(10000,)

In [15]:
w.shape

(11, 10000)

In [16]:
wans = np.matmul(w, Y)

In [17]:
wans.shape

(11,)

In [18]:
wans

array([ 7.86133660e+01, -6.62888374e+01,  1.03043818e+00, -1.07014147e+01,
        1.29102503e+01, -1.47540654e-02, -9.17199608e-03, -1.83002187e-01,
        1.23534618e-02, -5.32862161e-02,  1.64002883e-01])

In [19]:
wans * X[0]

array([ 7.86133660e+01, -8.02351918e+01, -3.40802809e+00, -3.66071357e+01,
        1.33060644e+02, -1.47540654e-02,  1.49358145e-03,  1.94075642e-02,
       -2.22260421e-03, -4.31661479e-03, -2.24141150e-02])

In [20]:
Y[0]

10.20992218893124

In [21]:
X[0]

array([ 1.        ,  1.21038768, -3.30735812,  3.42077535, 10.30658903,
        1.        , -0.16284148, -0.106051  , -0.17991752,  0.08100809,
       -0.13666903])

In [22]:
wans * X[0].T

array([ 7.86133660e+01, -8.02351918e+01, -3.40802809e+00, -3.66071357e+01,
        1.33060644e+02, -1.47540654e-02,  1.49358145e-03,  1.94075642e-02,
       -2.22260421e-03, -4.31661479e-03, -2.24141150e-02])

In [23]:
X[0]

array([ 1.        ,  1.21038768, -3.30735812,  3.42077535, 10.30658903,
        1.        , -0.16284148, -0.106051  , -0.17991752,  0.08100809,
       -0.13666903])

In [24]:
np.matmul(wans, X[0])

91.40084806722737

In [25]:
arr = np.linalg.eigvals(XTX)

In [26]:
max(arr)

8443443.058774184

In [27]:
arr

array([8.44344306e+06, 1.79747578e+04, 4.43984101e+03, 1.46363174e+03,
       8.81886019e-11, 1.95672201e+02, 9.71214808e+01, 9.84646337e+01,
       9.93402805e+01, 1.02436430e+02, 1.01122700e+02])

In [28]:
min(arr)

8.81886018975463e-11

In [29]:
np.linalg.det(XTX)

6.4481030892797075e+19

In [74]:
wstart = [1] * 11

In [75]:
wstart

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [76]:
alpha = 1.18435097e-7

In [77]:
alpha

1.18435097e-07

In [78]:
wstart = wstart - alpha * (np.matmul(XTX, wstart) - np.matmul(X.T, Y))

In [79]:
wstart

array([1.06045597, 1.23507428, 0.87907088, 1.53060452, 3.13839116,
       1.04811031, 0.9998754 , 1.00002198, 1.00005332, 0.99999914,
       0.99993351])

In [89]:
for i in range(1, 100000):
    wstart = wstart - alpha * (np.matmul(XTX, wstart) - np.matmul(X.T, Y))

In [90]:
wstart

array([ -4.32469839, -11.56751808,   1.00834872, -29.45973454,
        12.85207262,   0.05185237,   0.27213229,   0.16547001,
         0.31109135,   0.20491191,   0.39178773])

In [44]:
wstart * X[0]

array([-3.73213665e+00, -1.44383474e+01, -3.40787741e+00, -1.01219135e+02,
        1.33058428e+02, -1.44294467e-02, -8.71534678e-04,  1.73111862e-02,
       -5.01889563e-03, -3.34258013e-03, -2.39882659e-02])

In [91]:
np.matmul(wstart, X[1])

141.56953303172327

In [92]:
Y[1]

139.5048537203942

In [105]:
Xtest = generate_data(1000, 10, True)
Xtest.shape

(1000, 11)

In [106]:
Ytest = compute_y(Xtest.T)

In [107]:
Ytest.shape

(1000,)

In [119]:
def pri(i):
    print(np.matmul(wstart, Xtest[i]))
    print(Ytest[i])

In [120]:
pri(15)

54.33101513704048
55.39137230478587


In [115]:
Ytest[3]

98.60490035595191

In [67]:
wans

array([ 7.86133660e+01, -6.62888374e+01,  1.03043818e+00, -1.07014147e+01,
        1.29102503e+01, -1.47540654e-02, -9.17199608e-03, -1.83002187e-01,
        1.23534618e-02, -5.32862161e-02,  1.64002883e-01])

In [123]:
def err(X, Y):
    el = 0
    for i in range(len(X)):
        tmp = abs(np.matmul(wans, X[i]) - Y[i]) ** 2
        el += tmp
    el = el / len(X)
    print(len(X))
    return el

print(err(X, Y))
print(err(Xtest, Ytest))

10000
2946.0702130410746
1000
2845.5322346879375


In [99]:
np.matmul(wstart, X[0])

9.922120010657139

In [100]:
Y[0]

10.20992218893124

In [122]:
arr = np.linalg.eigvals(XTX)
print(max(arr))
print(min(arr))

8443443.058774184
8.81886018975463e-11


In [101]:
import math
import numpy as np 

def generate_data_lin_reg(size, d):
    x = []
    x.append(np.ones(size)) #add a column of 1's now to reflect the bias term in a linear regression model
    #the rest stays the same
    x.append(np.random.normal(3, 1, size)) #X_1 as per the problem
    x.append(np.random.normal(-2, 1, size)) #X_2
    x.append(x[1] + 2 * x[2]) #X_3
    x.append((x[2] + 2)**2) #X_4
    x.append(np.random.binomial(n=1, p=0.8, size=size)) #X_5
    for _ in range(d - 5): #if d > 5, then we add d - 5 additional normally distributed random variables
        x.append(np.random.normal(0, 0.1, size))

    def compute_y(x): #use this helper function to compute the y value based on the model in the problem statement
        y = 4 - 3 * x[1] * x[1] + x[3] - 0.01 * x[4] + x[2] * x[5] + np.random.normal(0, 0.1, len(x[0]))
        return y
    
    def transpose(temp): #a helper method to compute the transpose of the list (also converts to numpy list)
        temp = np.array(temp)
        return temp.T
    
    xt = transpose(x)
    y = compute_y(x)
    
    return np.array(x), xt, y 

def compute_mse_lin_reg(x, y, w):
    err = 0 #err
    for i in range(len(x)):
        err += abs(np.matmul(w, x[i]) - y[i]) ** 2 #compute the squared error
    err = err / len(x) #mean of the errors
    return err

In [24]:
def compute_mse_lin_reg(x, y, w):
    err = 0
    for i in range(len(x)):
        err += abs(np.matmul(w, x[i]) - y[i]) ** 2
    err = err / len(x)
    return err

In [ ]:
x, xt, y = generate_data(10000, D)

wstart = [1] * d
xt = x.T
xtx = np.matmul(xt, x)
for i in range(1, 100000):
    wstart = wstart - alpha * (np.matmul(xtx, wstart) - np.matmul(xt, y))
return wstart

In [15]:
xt, x, y = generate_data_lin_reg(10000, D)
print(type(x))

<class 'numpy.ndarray'>


In [36]:
xt, x, y = generate_data_lin_reg(10000, D)
_, testx, testy = generate_data_lin_reg(1000, D)

w = [1] * (D + 1)

xtx = np.matmul(xt, x)

alpha = 1.18435097e-7
iterations = 10000

for i in range(0, iterations):
    w = w - alpha * (np.matmul(xtx, w) - np.matmul(xt, y))
    
train_err = compute_mse_lin_reg(x, y, wstart)
test_err = compute_mse_lin_reg(testx, testy, wstart)

print('Training Error: ', train_err)
print('Testing Error: ', test_err)

Training Error:  7.555360110216522
Testing Error:  8.191812903824442


In [28]:
x.shape

(10000, 11)

(10000, 51)
(10000, 51)
[1.81718432e+05 5.53191841e+04 2.00140367e+04 2.09789090e+03
 4.76874318e+02 2.24432226e-11 1.13281753e+02 1.12359067e+02
 8.73685055e+01 1.11565361e+02 1.10723095e+02 1.10634894e+02
 8.86323801e+01 1.08941625e+02 8.95117923e+01 1.08126940e+02
 9.01527515e+01 9.09127660e+01 9.13708315e+01 9.12977568e+01
 9.19373271e+01 1.07707809e+02 1.07123308e+02 1.06571335e+02
 1.06064784e+02 1.05879619e+02 9.33661519e+01 1.04852658e+02
 1.04450474e+02 9.41255435e+01 1.04144167e+02 9.45668149e+01
 9.48557671e+01 9.51457622e+01 9.56393527e+01 9.62002541e+01
 9.65583165e+01 1.03250427e+02 1.02799228e+02 1.02563831e+02
 1.02095181e+02 1.01654964e+02 1.01095723e+02 1.00699670e+02
 9.73201306e+01 9.76221490e+01 9.80210088e+01 9.81837166e+01
 9.98248544e+01 9.93728914e+01 9.89890356e+01]
1419400.2821072964
1419400.2821072964
275917.9506798078
194649.4732615128
138644.81926246744
100304.54331994291
74326.71797957455
56976.64325342002
45578.27554844614
38185.4892976093
33394.80640845

929.388121234853
927.31993926136
925.2575994485887
923.20108643164
921.1503848846007
919.1054795183586
917.066355081929
915.0329963616317
913.0053881819605
910.9835154041166
908.9673629265884
906.9569156851285
904.9521586531957
902.953076839947
900.9596552924913
898.9718790942466
896.9897333650945
895.0132032617298
893.0422739771736
891.0769307409392
889.1171588185881
887.1629435118637
885.2142701584601
883.2711241319147
881.3334908421948
879.4013557341591
877.4747042889692
875.5535220227384
873.6377944876098
871.7275072704938
869.822645993697
867.9231963150058
866.029143926547
864.1404745560662
862.2571739656444
860.3792279525419
858.5066223482384
856.6393430189457
854.7773758652269
852.920706822114
851.0693218585764
849.2232069783571
847.3823482186036
845.5467316507912
843.7163433801933
841.8911695457595
840.0711963203177
838.2564099097203
836.4467965540625
834.6423425266044
832.8430341334267
831.048857714246
829.259799642138
827.4758463226882
825.6969841941819
823.923199728857
822.1

242.1874999346979
242.022328902308
241.8573923025978
241.69268937014954
241.52821934269141
241.363981461135
241.19997496936793
241.03619911452859
240.87265314672845
240.70933631909244
240.5462478879034
240.38338711244288
240.2207532550055
240.05834558088645
239.89616335849342
239.73420585904717
239.57247235689778
239.41096212925513
239.2496744565139
239.08860862165673
238.92776391089285
238.76713961311458
238.60673502039856
238.44654942754252
238.28658213230446
238.126832435158
237.96729963969676
237.80798305225593
237.64888198189777
237.48999574058013
237.33132364331237
237.17286500748972
237.01461915366787
236.85658540500447
236.69876308759726
236.5411515300629
236.38375006387724
236.22655802337056
236.06957474553846
235.91279956995032
235.75623183912037
235.59987089810326
235.44371609470815
235.28776677945527
235.13202230542896
234.976482028429
234.82114530688744
234.66601150185292
234.51107997706072
234.35635009887721
234.20182123611676
234.04749276043444
233.8933640456703
233.7394

135.09274259940773
135.01802383331278
134.94334787113553
134.86871468253415
134.794124237248
134.7195765050631
134.64507145579415
134.5706090593235
134.49618928554776
134.42181210444946
134.34747748601862
134.27318540033914
134.19893581748502
134.12472870762193
134.05056404093202
133.976441787652
133.9023619180747
133.82832440252753
133.75432921137144
133.68037631503552
133.606465683971
133.53259728870057
133.4587710997491
133.3849870877422
133.31124522329307
133.2375454771036
133.1638878198858
133.0902722224018
133.0166986555026
132.94316708999574
132.86967749680468
132.79622984687646
132.72282411118277
132.6494602607631
132.57613826665798
132.50285810001893
132.42961973197563
132.35642313373663
132.2832682765223
132.2101551316201
132.13708367035144
132.06405386408073
131.99106568420385
131.91811910218092
131.84521408948729
131.77235061764887
131.69952865823356
131.62674818284694
131.55400916313553
131.4813115707986
131.40865537755306
131.33604055517145
131.2634670754588
131.190934910

79.93099258591407
79.88710271994462
79.84323712338349
79.7993957826698
79.75557868422626
79.71178581450953
79.66801715996243
79.62427270705741
79.58055244225497
79.53685635203333
79.49318442287773
79.44953664127814
79.40591299373934
79.36231346675989
79.31873804686829
79.27518672057847
79.23165947443027
79.18815629495475
79.14467716870503
79.10122208223076
79.05779102210212
79.01438397488424
78.9710009271618
78.927641865516
78.88430677653982
78.84099564683908
78.79770846302677
78.75444521171498
78.71120587952912
78.6679904531088
78.62479891908612
78.58163126412241
78.53848747486072
78.49536753797334
78.45227144012767
78.40919916801498
78.36615070831
78.3231260477126
78.28012517292898
78.23714807066744
78.1941947276453
78.1512651305919
78.10835926623591
78.06547712132716
78.0226186826121
77.97978393684781
77.93697287079178
77.89418547122588
77.85142172493241
77.80868161869289
77.76596513930217
77.72327227356803
77.6806030082977
77.6379573303137
77.59533522644271
77.55273668350765
77.510

48.609712989586896
48.583109123885144
48.556519912416334
48.52994534705103
48.50338541967482
48.4768401221661
48.45030944641747
48.42379338432256
48.39729192777778
48.37080506868506
48.344332798949374
48.31787511048495
48.29143199520695
48.265003445031795
48.23858945188951
48.21219000771033
48.185805104422805
48.159434733967835
48.133078888289056
48.10673755933027
48.0804107390451
48.05409841939414
48.02780059233346
48.00151724983019
47.97524838385305
47.94899398637602
47.92275404937976
47.8965285648446
47.87031752476181
47.84412092112001
47.81793874591801
47.79177099115703
47.765617648839296
47.7394787109827
47.713354169590694
47.68724401669388
47.66114824430632
47.63506684445996
47.608999809186486
47.58294713052452
47.556908800516716
47.530884811196756
47.50487515463281
47.47887982286515
47.45289880796026
47.42693210197651
47.40097969698659
47.37504158505959
47.349117758274325
47.323208208713325
47.29731292845694
47.2714319095982
47.24556514423008
47.21971262445441
47.19387434237387


29.49624942169807
29.480158119669863
29.464075652438446
29.448002015114778
29.431937202830618
29.41588121070243
29.399834033853956
29.38379566742168
29.36776610653264
29.351745346321472
29.335733381929806
29.319730208489638
29.303735821151264
29.28775021505355
29.271773385344968
29.255805327181765
29.239846035711516
29.223895506095975
29.207953733484835
29.19202071305021
29.176096439946814
29.16018090934945
29.144274116423624
29.128376056337725
29.11248672427358
29.096606115403542
29.08073422491214
29.064871047979143
29.049016579792344
29.033170815533623
29.017333750399526
29.001505379586515
28.985685698285916
28.969874701696376
28.954072385024272
28.93827874346453
28.922493772236006
28.906717466539998
28.890949821590908
28.875190832604865
28.85944049479758
28.843698803391582
28.827965753608087
28.812241340671246
28.796525559813343
28.780818406262902
28.76511987525347
28.749429962020432
28.73374866180357
28.7180759698434
28.702411881385096
28.68675639167657
28.67110949596608
28.6554711

17.579282002715956
17.569723627851612
17.560170483420244
17.55062256653552
17.541079874320552
17.531542403894857
17.522010152390134
17.51248311692838
17.50296129463262
17.493444682640202
17.48393327807431
17.474427078071088
17.464926079765508
17.455430280290766
17.44593967678486
17.436454266382597
17.426974046231997
17.41749901346831
17.408029165238798
17.39856449868373
17.389105010954278
17.379650699200656
17.370201560564958
17.36075759220225
17.351318791267182
17.341885154913605
17.332456680293536
17.32303336456803
17.31361520489802
17.30420219843815
17.294794342358532
17.285391633819497
17.27599406998441
17.26660164802168
17.257214365102115
17.247832218390162
17.238455205066032
17.229083322297228
17.21971656725996
17.21035493712948
17.200998429086525
17.19164704030875
17.18230076797814
17.172959609276184
17.163623561387197
17.154292621499476
17.144966786797305
17.13564605447145
17.126330421711916
17.117019885711585
17.107714443663774
17.09841409275945
17.089118830202757
17.079828653

10.73077234998773
10.724956085732956
10.71914299409712
10.713333073340042
10.707526321716413
10.70172273749263
10.695922318925195
10.690125064279146
10.684330971817866
10.678540039804517
10.672752266503108
10.666967650180085
10.661186189107001
10.655407881543864
10.649632725764176
10.643860720039386
10.638091862637118
10.632326151830515
10.62656358589428
10.620804163099242
10.615047881720992
10.609294740034352
10.60354473631557
10.597797868844987
10.592054135898701
10.586313535756853
10.580576066696079
10.574841727005271
10.569110514963159
10.5633824288502
10.557657466957856
10.551935627560827
10.54621690895286
10.540501309418872
10.534788827244276
10.529079460722768
10.523373208138723
10.517670067788922
10.511970037965051
10.506273116951697
10.500579303050761
10.494888594551295
10.489200989752302
10.483516486951803
10.477835084440768
10.472156780525447
10.46648157350084
10.460809461660828
10.455140443320905
10.449474516772694
10.443811680319923
10.438151932271673
10.432495270926035
10

6.468913538613413
6.465418556953409
6.4619254755407365
6.458434293332304
6.454945009289858
6.451457622376378
6.4479721315513885
6.444488535779593
6.441006834024467
6.437527025242802
6.43404910840907
6.430573082483636
6.427098946429292
6.423626699216798
6.420156339809247
6.416687867174805
6.413221280279712
6.409756578095052
6.406293759589589
6.402832823730923
6.399373769487482
6.395916595833731
6.392461301737887
6.389007886175474
6.385556348110371
6.382106686521382
6.378658900385402
6.375212988669892
6.37176895035048
6.368326784405358
6.364886489806659
6.361448065532641
6.3580115105575805
6.354576823861082
6.351144004421594
6.347713051215609
6.344283963222922
6.34085673942409
6.337431378796252
6.334007880323394
6.3305862429828546
6.327166465764155
6.323748547640117
6.320332487600771
6.316918284622986
6.313505937697235
6.310095445804122
6.30668680792884
6.30328002306366
6.299875090184778
6.296472008284936
6.29307077634987
6.289671393371578
6.286273858331492
6.282878170223219
6.2794843280

3.845497532901888
3.8434267590068782
3.841357107276888
3.8392885770912266
3.837221167842636
3.8351548789198184
3.8330897097130547
3.8310256596079832
3.8289627279944316
3.8269009142692196
3.824840217814118
3.822780638025285
3.8207221742889823
3.818664826001933
3.816608592556401
3.814553473337595
3.812499467742585
3.810446575163564
3.808394794994736
3.8063441266269282
3.80429456945731
3.8022461228754456
3.8001987862779205
3.798152559062726
3.796107440616982
3.794063430345447
3.7920205276374865
3.7899787318912352
3.7879380425034337
3.785898458867668
3.783859980390674
3.781822606453999
3.779786336468207
3.7777511698284347
3.775717105930309
3.7736841441728877
3.771652283957604
3.7696215246836973
3.767591865746515
3.765563306553313
3.7635358464980233
3.761509484986978
3.7594842214141475
3.75746005518623
3.755436985701389
3.7534150123670402
3.7513941345767936
3.7493743517434908
3.7473556632640586
3.745338068541869
3.7433215669825555
3.741306157987246
3.7392918409623834
3.7372786153133477
3.73

2.2923562040555296
2.291125818635112
2.289896097772469
2.2886670411117467
2.287438648285374
2.2862109189323587
2.2849838526974118
2.283757449215159
2.2825317081311716
2.28130662907704
2.2800822116987756
2.2788584556386233
2.2776353605330617
2.2764129260224477
2.275191151748876
2.273970037355256
2.2727495824815382
2.2715297867678896
2.2703106498598915
2.269092171394227
2.2678743510189636
2.2666571883713686
2.2654406830982805
2.264224834839002
2.2630096432349185
2.2617951079340664
2.2605812285755498
2.259368004807269
2.258155436268595
2.256943522605886
2.2557322634620642
2.2545216584828487
2.253311707310035
2.252102409591589
2.2508937649707956
2.249685773094371
2.2484784336043857
2.247271746146214
2.2460657103682893
2.244860325915983
2.2436555924334756
2.2424515095694706
2.2412480769668197
2.2400452942768125
2.2388431611445894
2.2376416772159557
2.2364408421354933
2.2352406555533224
2.234041117119214
2.2328422264800984
2.231643983283112
2.2304463871735156
2.229249437803413
2.228053134820

1.4494907603489773
1.4487150150684747
1.4479396875695827
1.4471647776228764
1.446390285005685
1.4456162094919436
1.4448425508510663
1.4440693088589907
1.4432964832957995
1.4425240739289378
1.4417520805331523
1.4409805028901201
1.4402093407647474
1.4394385939377008
1.4386682621830362
1.4378983452742768
1.4371288429905398
1.4363597551029494
1.4355910813891186
1.4348228216211805
1.4340549755812857
1.4332875430368415
1.432520523772985
1.431753917559041
1.4309877241735731
1.4302219433929824
1.4294565749949246
1.428691618751353
1.427927074440655
1.4271629418426517
1.42639922073347
1.4256359108854109
1.4248730120833268
1.4241105241003227
1.423348446713434
1.4225867797003977
1.4218255228367587
1.4210646759055399
1.4203042386812765
1.41954421094081
1.4187845924631706
1.418025383026534
1.4172665824124382
1.4165081903968761
1.4157502067571006
1.4149926312728456
1.4142354637230141
1.4134787038880612
1.4127223515444502
1.411966406475194
1.4112108684549234
1.4104557372677036
1.409701012686125
1.4089

0.8940535868758944
0.8935765548007788
0.8930997788536169
0.8926232588897801
0.8921469947734127
0.8916709863632194
0.8911952335276917
0.8907197361196082
0.8902444940069694
0.8897695070519516
0.8892947751200296
0.8888202980631384
0.8883460757503269
0.8878721080436983
0.8873983948063258
0.8869249358983248
0.8864517311797648
0.8859787805217907
0.8855060837783232
0.8850336408194249
0.8845614515047155
0.8840895156951033
0.8836178332556773
0.8831464040514344
0.8826752279442583
0.8822043047927386
0.8817336344668084
0.8812632168285959
0.8807930517407594
0.8803231390672764
0.8798534786650358
0.8793840704085274
0.8789149141584326
0.8784460097722484
0.8779773571227815
0.8775089560657633
0.8770408064711461
0.8765729082010006
0.876105261122368
0.8756378650929987
0.8751707199838251
0.8747038256566652
0.874237181974513
0.8737707888045538
0.8733046460121395
0.8728387534596705
0.8723731110132562
0.8719077185332825
0.8714425758918369
0.8709776829517281
0.8705130395748015
0.8700486456288185
0.869584500979

0.5496255163124975
0.5493331508364504
0.5490409418543877
0.5487488892773242
0.5484569930277913
0.5481652530170941
0.5478736691629643
0.5475822413821071
0.5472909695850658
0.5469998536976192
0.5467088936242598
0.5464180892911076
0.5461274406099287
0.5458369474955918
0.5455466098671339
0.5452564276384659
0.5449664007254852
0.5446765290485397
0.5443868125207696
0.5440972510573765
0.5438078445793991
0.5435185930015277
0.5432294962363281
0.5429405542023953
0.5426517668257267
0.5423631340104417
0.542074655674435
0.5417863317371849
0.5414981621218853
0.5412101467352443
0.5409222855021989
0.540634578335393
0.5403470251507935
0.5400596258676577
0.5397723804050262
0.539485288676305
0.539198350599489
0.5389115660915751
0.5386249350745955
0.5383384574603662
0.5380521331686191
0.5377659621137162
0.5374799442181284
0.5371940793956762
0.5369083675687045
0.5366228086455423
0.5363374025511819
0.5360521492047132
0.5357670485181226
0.5354821004141594
0.5351973048086834
0.5349126616151323
0.53462817075890

0.3183636567157545
0.3181948845864631
0.3180262024870741
0.31785761036358834
0.3176891081715577
0.3175206958668625
0.3173523733931124
0.3171841407070234
0.3170159977611163
0.31684794450139225
0.31667998088889404
0.31651210686743614
0.3163443223925553
0.3161766274142066
0.31600902188889557
0.3158415057630428
0.31567407899245026
0.3155067415273327
0.3153394933189418
0.31517233432165725
0.31500526448927224
0.3148382837668961
0.31467139211321066
0.31450458947728943
0.3143378758138807
0.31417125107137456
0.31400471520761875
0.31383826816949323
0.3136719099086676
0.3135056403837958
0.3133394595432224
0.31317336734048845
0.31300736372358434
0.3128414486543813
0.31267562207316985
0.31250988394438645
0.31234423421562296
0.31217867283659145
0.3120131997630929
0.311847814946478
0.31168251834024574
0.3115173098967833
0.3113521895669949
0.31118715730796204
0.31102221306965755
0.3108573568044803
0.31069258846067466
0.31052790800112706
0.310363315372031
0.31019881052756454
0.31003439342143396
0.30987

0.19757835657182965
0.19747392626501592
0.19736955149914404
0.19726523224329634
0.19716096846947828
0.19705676014320175
0.19695260724115277
0.1968485097311796
0.19674446758060254
0.19664048076271934
0.19653654924485173
0.19643267300258702
0.19632885200452133
0.1962250862183702
0.1961213756136034
0.19601772016670088
0.19591411984572354
0.19581057462011572
0.19570708445818275
0.1956036493346511
0.1955002692171295
0.19539694407896868
0.1952936738896745
0.19519045861923154
0.19508729823313165
0.19498419271340536
0.1948811420218631
0.19477814613367342
0.1946752050154197
0.19457231864160957
0.19446948698210162
0.19436671000269345
0.19426398768143882
0.19416131998726088
0.19405870688449112
0.19395614835378108
0.19385364436217795
0.19375119487566375
0.19364879987085298
0.1935464593164925
0.1934441731844001
0.1933419414397451
0.1932397640653201
0.19313764102301417
0.19303557228554272
0.19293355782297383
0.1928315976085374
0.19272969161062734
0.1926278398024904
0.19252604215433272
0.192424298640

0.11697939521519539
0.11691776625501765
0.11685616996078999
0.11679460631793377
0.11673307531245636
0.11667157692262044
0.11661011113085189
0.11654867792336367
0.11648727727831049
0.11642590918169589
0.11636457361584635
0.11630327056147648
0.11624200000386166
0.11618076192205609
0.11611955630254314
0.11605838312859336
0.11599724237777305
0.11593613403513904
0.11587505808619375
0.11581401451090655
0.11575300329242628
0.11569202441560653
0.11563107785584452
0.11557016360670778
0.1155092816428894
0.11544843195173914
0.11538761451091607
0.11532682930943941
0.11526607632621126
0.11520535554546141
0.11514466694933043
0.11508401051924105
0.11502338624170819
0.11496279409580468
0.11490223406661974
0.11484170613820975
0.11478121029032314
0.11472074650814952
0.11466031477044207
0.11459991506804514
0.11453954737605007
0.11447921168143788
0.11441890796660033
0.11435863621488677
0.1142983964056867
0.11423818852886816
0.11417801255890268
0.11411786848614837
0.11405775629239139
0.11399767595584455
0.

In [119]:
w

array([ 3.00063054e+01, -1.48980486e+01,  7.32566313e+00, -2.24672238e+00,
       -3.61987283e-02, -1.86236163e+00, -1.36249175e-01, -6.34393069e-01,
       -1.86416144e-01,  7.76176983e-02,  1.71586898e-01, -2.06365162e-01,
       -1.08621332e-01,  3.54287182e-01,  2.89653259e-01,  4.35969765e-02,
       -6.79135708e-01,  3.77986164e-01,  7.33494532e-02, -3.12640901e-01,
       -3.68927485e-01, -3.20825384e-02, -1.39767533e-01, -6.97112576e-02,
       -1.09580327e-01,  3.27809048e-01,  1.43773149e-01, -8.30817316e-02,
        5.68652820e-02,  8.12870259e-02, -2.76845333e-01,  1.37834751e-01,
        5.30664886e-01,  1.18580514e-01,  1.56380845e-01, -2.82465461e-01,
       -3.89441921e-01,  2.33089141e-01,  9.76329271e-03,  3.31111122e-01,
       -3.64536371e-01,  3.21213586e-01,  4.42866853e-02,  3.54027329e-01,
        5.01030178e-01, -1.40518649e-01, -4.57146035e-01, -5.71605037e-02,
        6.84332099e-01, -2.39821190e-01,  1.08960545e-01])

In [120]:
len(w)

51

In [167]:
import copy
import matplotlib.pyplot as plt

def gradient_descent(x, xt, y, testx, testy):
    w = [1] * len(xt)
    xtx = np.matmul(xt, x)
    
    def find_alpha(xtx): 
        eigvals = np.linalg.eigvals(xtx)
        mx = np.max(eigvals)
        return 1 / mx
    
    alpha = find_alpha(xtx) 
    grad = np.matmul(xtx, w) - np.matmul(xt, y)
    cnt = 0
    
    while np.linalg.norm(grad) > 0.1:
        cnt += 1
        grad = np.matmul(xtx, w) - np.matmul(xt, y)
        w = w - alpha * grad 
    
    train_err = compute_mse_lin_reg(x, y, w) #training_error
    test_err = compute_mse_lin_reg(testx, testy, w) #test_error
    
    print('Iterations: ', cnt)
    print('Alpha used: ', alpha)
    print('Training Error: ', train_err)
    print('Testing Error: ', test_err)
    
    return w


def question8(x, xt, y, testx, testy, w):
    
    epss = np.linspace(0, 1.5, num = 19) #all possible epsilons
    test_errors = []
    
    for eps in epss:
        wcpy = copy.deepcopy(w)
        fltr = abs(wcpy) > eps
        
        xt_fltred = xt[fltr]
        
        _, w_new, _, _ = gradient_descent(xt_fltred.T, xt_fltred, y, testx, testy, 0, len(xt_fltred) - 1)
        test_err = compute_mse_lin_reg(testx, testy, w_new) #test_error
        test_errors.append(test_err)
        print(test_err)
        
    plt.title('Epsilon and Testing Dataset Error')
    plt.xlabel('Epsilon')
    plt.ylabel('Test Error')
    plt.plot(epss, test_errors)
    plt.show()
    
    return epss, test_errors

xt, x, y = generate_data_lin_reg(10000, 50)
_, testx, testy = generate_data_lin_reg(1000, 50)
w = gradient_descent(x, xt, y, testx, testy)


Iterations:  17106
Alpha used:  5.445001554750128e-06
Training Error:  17.30384808862131
Testing Error:  20.935871906294135


In [163]:
print(w)

[ 2.90656989e+01 -1.46509089e+01  7.22113049e+00 -2.20864792e+00
 -1.85220732e-02 -1.89862769e+00  2.99220620e-01 -1.39511386e-01
  3.51413499e-01 -3.14311020e-01  4.84352174e-01  5.77638441e-01
 -4.16608106e-01 -1.36528787e-01  5.09507194e-02 -1.07904611e-01
 -4.64536556e-02  8.48352293e-02  9.19633401e-01 -9.40671821e-01
 -6.65972355e-01  1.25122393e-01  7.41196494e-02 -1.09149157e-02
  7.52430863e-01  1.43095396e-01  5.45251330e-01 -8.60823352e-02
  6.98923968e-01 -4.17451765e-01  1.09531218e+00  3.50999318e-01
 -1.57636989e-01 -6.07056833e-01  2.02234674e-01 -1.94481149e-01
 -2.11087223e-01  3.63072731e-01 -1.03969761e+00 -1.45895205e-01
  4.02494883e-01 -1.88273726e-01 -2.19520241e-01 -5.53670254e-01
  1.15675120e+00  3.05002090e-01 -2.91045102e-02 -6.16466982e-01
 -7.41199659e-01 -4.83873887e-01 -2.59395167e-02]
